- hosts: ansible_host
  gather_facts: no

  tasks:

    - name: Build and Push Image
      docker_image:
        build:
          path: /home/ubuntu/hello-world
        name: ordahsmaesa/hello-world

        push: yes
        source: build
