- hosts: ansible_host
  gather_facts: no
  tasks:
    - name: Create Deployment
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: hello-world
            namespace: default
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: hello-world
            template:
              metadata:
                labels:
                  app: hello-world
              spec:
                containers:
                  - name: hello-world
                    image: "ordahsmaesa/hello-world"
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 8080 
    - name: Create Service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: hello-world-svc
            namespace: default
          spec:
            type: NodePort
            selector:
              app: hello-world
            ports:
              - port: 80
                targetPort: 8080
                nodePort: 31313
